defaults:
  - env: entity
  - learning: 
    - ppo-base
    - ppo-ued
  - misc: misc
  - env_size: s
  - eval: s
  - ued: plr
  - train_levels: random
  - model: 
    - model-base
    - model-transformer
    - model-perm-invariant-mlp
  - _self_

seed: 0